name: SparkPlugins CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Package
      run: sbt package
    - uses: actions/upload-artifact@v2
      with:
        name: SparkPlugins package scala 2.12
        path: /home/runner/work/SparkPlugins/SparkPlugins/target/scala-2.12/*.jar

